version: "3.2"
services:
    nodejs:
      image: ciao/threejsfirstprj
      depends_on:
        - mysql
      environment:
        MYSQL_DATABASE: db
        MYSQL_USER: lore
        MYSQL_PASSWORD: lore
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./www/:/var/www/html
      ports:
        - 30001:8005
      networks:
        - frontend 
        - backend
      container_name: node-app
    mysql:
      image: mysql:5.7
      restart: always
      networks:
          - backend
      environment:
         MYSQL_DATABASE: db
         MYSQL_USER: lore
         MYSQL_PASSWORD: lore
         MYSQL_ROOT_PASSWORD: root
      container_name: mysql-app
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:4.7
      depends_on:
        - mysql
      networks:
        - backend
      ports:
        - 30002:80
      environment:
        - PMA_HOST=node-app
        - PMA_PASSWORD=root
        - PMA_PORT_3306
      volumes:
        - /session
      container_name: phpMA-app
networks:
    frontend:
    backend: 


